export const teams = [
    "Connecticut",
    "Houston",
    "Purdue",
    "N Carolina",
    "Tennessee", 
    "Arizona",
    "Marquette",
    "Iowa St",
    "Baylor",
    "Creighton", 
    "Kentucky", 
    "Illinois", 
    "Duke", 
    "Kansas", 
    "Auburn",
    "Alabama", 
    "BYU", 
    "San Diego St",
    "Wisconsin", 
    "St Marys",
    "Gonzaga",
    "Clemson", 
    "Texas Tech",
    "S Carolina",
    "Florida", 
    "Wash State",
    "Texas", 
    "Dayton", 
    "Nebraska", 
    "Utah St",
    "Fla Atlantic", 
    "Miss State", 
    "Michigan St",
    "Texas A&M",
    "TX Christian", 
    "Northwestern",
    "Nevada",
    "Boise St",
    "Colorado",
    "Drake", 
    "Virginia",
    "New Mexico", 
    "Oregon", 
    "Colorado St", 
    "NC State", 
    "Duquesne",
    "Grd Canyon", 
    "James Mad", 
    "McNeese St", 
    "UAB", 
    "Vermont",
    "Yale", 
    "Samford",
    "Col Charlestn", 
    "Oakland", 
    "Akron", 
    "Morehead St",
    "Colgate", 
    "W Kentucky",
    "Lg Beach St", 
    "S Dakota St", 
    "St Peters", 
    "Longwood",
    "Stetson", 
    "Montana St", 
    "Grambling St", 
    "Howard", 
    "Wagner" 
]
  